const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const STEPINCREMENT = 'STEPINCREMENT';
const STEPDECREMENT = 'STEPDECREMENT';

export { INCREMENT, DECREMENT, STEPINCREMENT, STEPDECREMENT };
